name: vitriol
favicon: null
layout_spectrum: 0
typography_spectrum: 0.6621966608799994
title: V.I.T.R.I.O.L 8
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0
  lightness: 0.9951547984965146
  saturation: 0.41051241639070213
  rhythmicContrast: 0.47557572019286454
purpose: []
